apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-fuchicorp-prod
  namespace: tools
spec:
  acme:
    #The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    #Email address used for ACME registration
    email: example@gmail.com
    #Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-sec-prod
    #Enable HTTP01 validations
    http01: {}